global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'php_api'
    static_configs:
      - targets: ['nginx:80']   # Nginx контейнер
    metrics_path: /metrics
